runtime: nodejs18
env: standard
service: default

handlers:
  - url: /.*
    script: auto
    secure: always

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 1
  max_instances: 2
